spring:
  application:
    name: spring-cloud-config-eureka-server-node
  profiles: config1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javaDeveloperBook/spring-cloud-config
          search-paths: /
          username: 747596887@qq.com
          password: wujie30013991
server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka

---
spring:
  application:
    name: spring-cloud-config-eureka-server-node
  profiles: config2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javaDeveloperBook/spring-cloud-config
          search-paths: /
          username: 747596887@qq.com
          password: wujie30013991
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
---
spring:
  application:
    name: spring-cloud-config-eureka-server-node
  profiles: config3
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javaDeveloperBook/spring-cloud-config
          search-paths: /
          username: 747596887@qq.com
          password: wujie30013991
server:
  port: 7003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka